import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';

import {
  buildRouteContracts,
  concreteDemoPath,
  readRouteTitleCatalog,
  readRouteManifestSource,
} from './generate-route-contracts.mjs';

const source = fs.readFileSync(new URL('../src/app/routing/routeManifest.tsx', import.meta.url), 'utf8');
const support = JSON.parse(fs.readFileSync(new URL('../config/demo-route-support.json', import.meta.url), 'utf8'));
const routes = readRouteManifestSource(source);
const routeTitles = readRouteTitleCatalog();

test('reads all route facts from the repository-owned manifest', () => {
  assert.equal(routes.length, 85);
  assert.equal(routes[0].path, '/');
  assert.equal(routes.at(-1).path, '*');
  assert.equal(source.includes('specs/rinspace-animate-ui-redesign'), false);
  assert.equal(source.includes('Generated by scripts/redesign'), false);
});

test('generates complete demo coverage and official metadata contracts', () => {
  const contracts = buildRouteContracts(routes, support, routeTitles);
  assert.equal(contracts.coverage.routeCount, 85);
  assert.deepEqual(contracts.coverage.summary, {
    interactive: 48,
    'read-only': 22,
    'production-only': 11,
    'not-yet-supported': 4,
  });
  assert.equal(contracts.coverage.routes.every((route) => route.testPath.startsWith('/')), true);
  assert.equal(contracts.coverage.playwright.cases.length, 16);
  assert.deepEqual(new Set(contracts.coverage.playwright.cases.map((item) => item.persona)), new Set(['guest', 'member']));
  assert.equal(contracts.metadata.routes.length, 85);
  assert.equal(contracts.metadata.staticHosting.dynamicHtmlInjection, false);
  assert.equal(contracts.metadata.routes.find((route) => route.path === '/a/:postId')?.htmlMode, 'dynamic-official');
  assert.equal(contracts.metadata.routes.find((route) => route.path === '/settings')?.htmlMode, 'client-only');
  assert.deepEqual(contracts.metadata.routes.find((route) => route.path === '/about')?.localizedTitles, {
    en: 'About',
    'zh-CN': '关于',
  });
  assert.equal(contracts.metadata.metadataTemplate.title, '{pageTitle} · {site.name}');
  assert.equal(JSON.stringify(contracts).includes('rinspace.com'), false);
});

test('fails when a route has no explicit support association', () => {
  const incomplete = structuredClone(support);
  incomplete.support.interactive = incomplete.support.interactive.filter((routePath) => routePath !== '/');
  assert.throws(() => buildRouteContracts(routes, incomplete, routeTitles), /support coverage drift.*missing: \//);
});

test('rejects route titles that hard-code an official site brand', () => {
  const brandedTitles = structuredClone(routeTitles);
  brandedTitles.en.about = 'About · Rinspace';
  assert.throws(() => buildRouteContracts(routes, support, brandedTitles), /without a hard-coded site brand/);
});

test('builds deterministic fixture paths for each dynamic content family', () => {
  assert.equal(concreteDemoPath('/books/:postId/read/:titleSlug', support.pathParameters), '/books/1040/read/paper-to-orbit');
  assert.equal(concreteDemoPath('/q/:postId/:titleSlug', support.pathParameters), '/q/1030/iterator-boundary-last-example');
  assert.equal(concreteDemoPath('/d/:postId/:titleSlug', support.pathParameters), '/d/1050/diagrams-before-proof');
  assert.equal(concreteDemoPath('/s/:postId/:titleSlug', support.pathParameters), '/s/1060/field-note-fixed-clock');
  assert.equal(concreteDemoPath('*', support.pathParameters), '/route-coverage-not-found');
});
